title: ðŸ“„ðŸ§‘ðŸ»â€ðŸ’»ðŸ‘¨â€ðŸ‘©â€ðŸ‘¦ðŸƒâ€â™‚ï¸
# email: nikola@applycolo.rs
description: >
  Nikola Paunovic - CV
github_username: paunik

# Build settings
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme